### ISSUE TITLE
CW3

### ISSUE THREAD

**Issue by Karr4** [oleksandrblazhko/ai-215-korchakovskij#20]
### Завдання 1:
Посилання на детальний опис Бд з лабораторної роботи номер 6
[DetailedDataSchema.json](https://github.com/oleksandrblazhko/ai-215-korchakovskij/blob/with-laboratory-work-6/2-SoftwareDesign/2.4-DetailedDataSchema/DetailedDataSchema.json)

Початковий код Технічної підтримки:

"description": "Technical Support details",
      "type": "object",
      "properties": {
        "technical_support_id": {
          "type": "number",
          "minimum": 0,
          "properties": {
            "specialization": {
              "description": "Спеціалізація фахівця",
              "type": "string",
              "minLength": 0,
              "maxLength": 30
            },
            "position": {
              "description": "Посада фахівця",
              "type": "string",
              "minLength": 0,
              "maxLength": 30
            },
            "user_id": {
              "description": "Посилання на дані технічного фахівця як користувача",
              "type": "number",
              "minimum": 0
            }
          },
          "required": ["specialization", "position", "user_id"]
        }

Додамо регулярний вираз до поля specialization, що забороняє вводити у поле спеціальні символи: 
`^(?!.*[/|\\#@%$]).{6,30}$`

Тепер код Технічної підтримки виглядає наступним чинном:

"description": "Technical Support details",
      "type": "object",
      "properties": {
        "technical_support_id": {
          "type": "number",
          "minimum": 0,
          "properties": {
            "specialization": {
              "description": "Спеціалізація фахівця",
              "type": "string",
              "pattern": "^(?!.*[/|\\#@%$]).{6,30}$"
            },
            "position": {
              "description": "Посада фахівця",
              "type": "string",
              "minLength": 0,
              "maxLength": 30
            },
            "user_id": {
              "description": "Посилання на дані технічного фахівця як користувача",
              "type": "number",
              "minimum": 0
            }
          },
          "required": ["specialization", "position", "user_id"]
        }

### Завдання 2

Посилання на UML діаграму програмних класів:
[UMLProgramClasses.jpg](https://github.com/oleksandrblazhko/ai-215-korchakovskij/blob/with-laboratory-work-6/2-SoftwareDesign/2.5-UMLProgramClasses/UMLProgramClasses.jpg)

Коментарі до UML - діаграми програмних класів
- Зв'язок User - Consumer: У Consumer присутній зовнішній ключ user, для розуміння який користувач відповідає данному споживачеві
- Зв'язок User - Technical_Support: У Technical_Supportприсутній зовнішній ключ user, для розуміння який користувач відповідає данному технічному саппорту
- Зв'язок User - annoyance: У annoyance присутній зовнішній ключ user, для розуміння якому користувачеві відповідає запис про роздратованність
- Зв'язок User - tempreture: У tempreture присутній зовнішній ключ user, для розуміння якому користувачеві відповідає запис про температуру
- Зв'язок tempreture - annoyance: У annoyance присутній зовнішній ключ tempreture, для розуміння якому запису про температуру відповідає запис про роздратованність
- Зв'язок tempreture - annoyance: У annoyance присутній зовнішній ключ tempreture, для розуміння якому запису про температуру відповідає запис про роздратованність
- Зв'язок World_Weather_Organization - tempreture: Для отримання запису про температуру, World_Weather_Organization надсилає дані про поточну температуру в регіоні
- Зв'язок tempreture - notification: Після отримання даних про температуру, додаток виводить дані у вигляді нотіфікації
- Зв'язок annoyance - notification: Після отримання даних про роздратованність, додаток виводить дані у вигляді нотіфікації
- Зв'язок Consumer - technical_question: У technical_question присутній зовнішній ключ consumer, для розуміння якому споживачеві відповідає дане технічне питання
- Зв'язок Technical_Support - technical_question: У technical_question присутній зовнішній ключ technical_support , для розуміння якому технічному саппорту відповідає дане технічне питання

**Comment by oleksandrblazhko** [comment]
3 бали
